version: '3.7'
services:
  nifi:
    container_name: eventify-adapter
    image: apache/nifi:latest
    user: root
    restart: always
    ports:
      - 8443:8443
      - 8079:8079
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=eventify
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456789012
      - NIFI_WEB_HTTP_PORT=8443
